// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecSys.Data;

namespace RecSys.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190413221453_BeforeSingleRecommendationTable")]
    partial class BeforeSingleRecommendationTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("RecSys.Models.CollaborativeNotPurchasedRecommendation", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Item1")
                        .HasMaxLength(20);

                    b.Property<string>("Item10")
                        .HasMaxLength(20);

                    b.Property<string>("Item11")
                        .HasMaxLength(20);

                    b.Property<string>("Item12")
                        .HasMaxLength(20);

                    b.Property<string>("Item13")
                        .HasMaxLength(20);

                    b.Property<string>("Item14")
                        .HasMaxLength(20);

                    b.Property<string>("Item15")
                        .HasMaxLength(20);

                    b.Property<string>("Item16")
                        .HasMaxLength(20);

                    b.Property<string>("Item17")
                        .HasMaxLength(20);

                    b.Property<string>("Item18")
                        .HasMaxLength(20);

                    b.Property<string>("Item19")
                        .HasMaxLength(20);

                    b.Property<string>("Item2")
                        .HasMaxLength(20);

                    b.Property<string>("Item20")
                        .HasMaxLength(20);

                    b.Property<string>("Item21")
                        .HasMaxLength(20);

                    b.Property<string>("Item22")
                        .HasMaxLength(20);

                    b.Property<string>("Item23")
                        .HasMaxLength(20);

                    b.Property<string>("Item24")
                        .HasMaxLength(20);

                    b.Property<string>("Item25")
                        .HasMaxLength(20);

                    b.Property<string>("Item26")
                        .HasMaxLength(20);

                    b.Property<string>("Item27")
                        .HasMaxLength(20);

                    b.Property<string>("Item28")
                        .HasMaxLength(20);

                    b.Property<string>("Item29")
                        .HasMaxLength(20);

                    b.Property<string>("Item3")
                        .HasMaxLength(20);

                    b.Property<string>("Item30")
                        .HasMaxLength(20);

                    b.Property<string>("Item31")
                        .HasMaxLength(20);

                    b.Property<string>("Item32")
                        .HasMaxLength(20);

                    b.Property<string>("Item33")
                        .HasMaxLength(20);

                    b.Property<string>("Item34")
                        .HasMaxLength(20);

                    b.Property<string>("Item35")
                        .HasMaxLength(20);

                    b.Property<string>("Item36")
                        .HasMaxLength(20);

                    b.Property<string>("Item37")
                        .HasMaxLength(20);

                    b.Property<string>("Item38")
                        .HasMaxLength(20);

                    b.Property<string>("Item39")
                        .HasMaxLength(20);

                    b.Property<string>("Item4")
                        .HasMaxLength(20);

                    b.Property<string>("Item40")
                        .HasMaxLength(20);

                    b.Property<string>("Item41")
                        .HasMaxLength(20);

                    b.Property<string>("Item42")
                        .HasMaxLength(20);

                    b.Property<string>("Item43")
                        .HasMaxLength(20);

                    b.Property<string>("Item44")
                        .HasMaxLength(20);

                    b.Property<string>("Item45")
                        .HasMaxLength(20);

                    b.Property<string>("Item46")
                        .HasMaxLength(20);

                    b.Property<string>("Item47")
                        .HasMaxLength(20);

                    b.Property<string>("Item48")
                        .HasMaxLength(20);

                    b.Property<string>("Item49")
                        .HasMaxLength(20);

                    b.Property<string>("Item5")
                        .HasMaxLength(20);

                    b.Property<string>("Item50")
                        .HasMaxLength(20);

                    b.Property<string>("Item6")
                        .HasMaxLength(20);

                    b.Property<string>("Item7")
                        .HasMaxLength(20);

                    b.Property<string>("Item8")
                        .HasMaxLength(20);

                    b.Property<string>("Item9")
                        .HasMaxLength(20);

                    b.Property<double?>("Rating1");

                    b.Property<double?>("Rating10");

                    b.Property<double?>("Rating11");

                    b.Property<double?>("Rating12");

                    b.Property<double?>("Rating13");

                    b.Property<double?>("Rating14");

                    b.Property<double?>("Rating15");

                    b.Property<double?>("Rating16");

                    b.Property<double?>("Rating17");

                    b.Property<double?>("Rating18");

                    b.Property<double?>("Rating19");

                    b.Property<double?>("Rating2");

                    b.Property<double?>("Rating20");

                    b.Property<double?>("Rating21");

                    b.Property<double?>("Rating22");

                    b.Property<double?>("Rating23");

                    b.Property<double?>("Rating24");

                    b.Property<double?>("Rating25");

                    b.Property<double?>("Rating26");

                    b.Property<double?>("Rating27");

                    b.Property<double?>("Rating28");

                    b.Property<double?>("Rating29");

                    b.Property<double?>("Rating3");

                    b.Property<double?>("Rating30");

                    b.Property<double?>("Rating31");

                    b.Property<double?>("Rating32");

                    b.Property<double?>("Rating33");

                    b.Property<double?>("Rating34");

                    b.Property<double?>("Rating35");

                    b.Property<double?>("Rating36");

                    b.Property<double?>("Rating37");

                    b.Property<double?>("Rating38");

                    b.Property<double?>("Rating39");

                    b.Property<double?>("Rating4");

                    b.Property<double?>("Rating40");

                    b.Property<double?>("Rating41");

                    b.Property<double?>("Rating42");

                    b.Property<double?>("Rating43");

                    b.Property<double?>("Rating44");

                    b.Property<double?>("Rating45");

                    b.Property<double?>("Rating46");

                    b.Property<double?>("Rating47");

                    b.Property<double?>("Rating48");

                    b.Property<double?>("Rating49");

                    b.Property<double?>("Rating5");

                    b.Property<double?>("Rating50");

                    b.Property<double?>("Rating6");

                    b.Property<double?>("Rating7");

                    b.Property<double?>("Rating8");

                    b.Property<double?>("Rating9");

                    b.HasKey("UserId");

                    b.ToTable("SQLexport_CollaborativeFiltering-506user-3similarity_NotPurchased");
                });

            modelBuilder.Entity("RecSys.Models.CollaborativeRecommendation", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Item1")
                        .HasMaxLength(20);

                    b.Property<string>("Item10")
                        .HasMaxLength(20);

                    b.Property<string>("Item11")
                        .HasMaxLength(20);

                    b.Property<string>("Item12")
                        .HasMaxLength(20);

                    b.Property<string>("Item13")
                        .HasMaxLength(20);

                    b.Property<string>("Item14")
                        .HasMaxLength(20);

                    b.Property<string>("Item15")
                        .HasMaxLength(20);

                    b.Property<string>("Item16")
                        .HasMaxLength(20);

                    b.Property<string>("Item17")
                        .HasMaxLength(20);

                    b.Property<string>("Item18")
                        .HasMaxLength(20);

                    b.Property<string>("Item19")
                        .HasMaxLength(20);

                    b.Property<string>("Item2")
                        .HasMaxLength(20);

                    b.Property<string>("Item20")
                        .HasMaxLength(20);

                    b.Property<string>("Item21")
                        .HasMaxLength(20);

                    b.Property<string>("Item22")
                        .HasMaxLength(20);

                    b.Property<string>("Item23")
                        .HasMaxLength(20);

                    b.Property<string>("Item24")
                        .HasMaxLength(20);

                    b.Property<string>("Item25")
                        .HasMaxLength(20);

                    b.Property<string>("Item26")
                        .HasMaxLength(20);

                    b.Property<string>("Item27")
                        .HasMaxLength(20);

                    b.Property<string>("Item28")
                        .HasMaxLength(20);

                    b.Property<string>("Item29")
                        .HasMaxLength(20);

                    b.Property<string>("Item3")
                        .HasMaxLength(20);

                    b.Property<string>("Item30")
                        .HasMaxLength(20);

                    b.Property<string>("Item31")
                        .HasMaxLength(20);

                    b.Property<string>("Item32")
                        .HasMaxLength(20);

                    b.Property<string>("Item33")
                        .HasMaxLength(20);

                    b.Property<string>("Item34")
                        .HasMaxLength(20);

                    b.Property<string>("Item35")
                        .HasMaxLength(20);

                    b.Property<string>("Item36")
                        .HasMaxLength(20);

                    b.Property<string>("Item37")
                        .HasMaxLength(20);

                    b.Property<string>("Item38")
                        .HasMaxLength(20);

                    b.Property<string>("Item39")
                        .HasMaxLength(20);

                    b.Property<string>("Item4")
                        .HasMaxLength(20);

                    b.Property<string>("Item40")
                        .HasMaxLength(20);

                    b.Property<string>("Item41")
                        .HasMaxLength(20);

                    b.Property<string>("Item42")
                        .HasMaxLength(20);

                    b.Property<string>("Item43")
                        .HasMaxLength(20);

                    b.Property<string>("Item44")
                        .HasMaxLength(20);

                    b.Property<string>("Item45")
                        .HasMaxLength(20);

                    b.Property<string>("Item46")
                        .HasMaxLength(20);

                    b.Property<string>("Item47")
                        .HasMaxLength(20);

                    b.Property<string>("Item48")
                        .HasMaxLength(20);

                    b.Property<string>("Item49")
                        .HasMaxLength(20);

                    b.Property<string>("Item5")
                        .HasMaxLength(20);

                    b.Property<string>("Item50")
                        .HasMaxLength(20);

                    b.Property<string>("Item6")
                        .HasMaxLength(20);

                    b.Property<string>("Item7")
                        .HasMaxLength(20);

                    b.Property<string>("Item8")
                        .HasMaxLength(20);

                    b.Property<string>("Item9")
                        .HasMaxLength(20);

                    b.Property<double?>("Rating1");

                    b.Property<double?>("Rating10");

                    b.Property<double?>("Rating11");

                    b.Property<double?>("Rating12");

                    b.Property<double?>("Rating13");

                    b.Property<double?>("Rating14");

                    b.Property<double?>("Rating15");

                    b.Property<double?>("Rating16");

                    b.Property<double?>("Rating17");

                    b.Property<double?>("Rating18");

                    b.Property<double?>("Rating19");

                    b.Property<double?>("Rating2");

                    b.Property<double?>("Rating20");

                    b.Property<double?>("Rating21");

                    b.Property<double?>("Rating22");

                    b.Property<double?>("Rating23");

                    b.Property<double?>("Rating24");

                    b.Property<double?>("Rating25");

                    b.Property<double?>("Rating26");

                    b.Property<double?>("Rating27");

                    b.Property<double?>("Rating28");

                    b.Property<double?>("Rating29");

                    b.Property<double?>("Rating3");

                    b.Property<double?>("Rating30");

                    b.Property<double?>("Rating31");

                    b.Property<double?>("Rating32");

                    b.Property<double?>("Rating33");

                    b.Property<double?>("Rating34");

                    b.Property<double?>("Rating35");

                    b.Property<double?>("Rating36");

                    b.Property<double?>("Rating37");

                    b.Property<double?>("Rating38");

                    b.Property<double?>("Rating39");

                    b.Property<double?>("Rating4");

                    b.Property<double?>("Rating40");

                    b.Property<double?>("Rating41");

                    b.Property<double?>("Rating42");

                    b.Property<double?>("Rating43");

                    b.Property<double?>("Rating44");

                    b.Property<double?>("Rating45");

                    b.Property<double?>("Rating46");

                    b.Property<double?>("Rating47");

                    b.Property<double?>("Rating48");

                    b.Property<double?>("Rating49");

                    b.Property<double?>("Rating5");

                    b.Property<double?>("Rating50");

                    b.Property<double?>("Rating6");

                    b.Property<double?>("Rating7");

                    b.Property<double?>("Rating8");

                    b.Property<double?>("Rating9");

                    b.HasKey("UserId");

                    b.ToTable("SQLexport_CollaborativeFiltering-506user-0similarity");
                });

            modelBuilder.Entity("RecSys.Models.EnsembleRecommendation", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Item1")
                        .HasMaxLength(20);

                    b.Property<string>("Item10")
                        .HasMaxLength(20);

                    b.Property<string>("Item11")
                        .HasMaxLength(20);

                    b.Property<string>("Item12")
                        .HasMaxLength(20);

                    b.Property<string>("Item13")
                        .HasMaxLength(20);

                    b.Property<string>("Item14")
                        .HasMaxLength(20);

                    b.Property<string>("Item15")
                        .HasMaxLength(20);

                    b.Property<string>("Item16")
                        .HasMaxLength(20);

                    b.Property<string>("Item17")
                        .HasMaxLength(20);

                    b.Property<string>("Item18")
                        .HasMaxLength(20);

                    b.Property<string>("Item19")
                        .HasMaxLength(20);

                    b.Property<string>("Item2")
                        .HasMaxLength(20);

                    b.Property<string>("Item20")
                        .HasMaxLength(20);

                    b.Property<string>("Item21")
                        .HasMaxLength(20);

                    b.Property<string>("Item22")
                        .HasMaxLength(20);

                    b.Property<string>("Item23")
                        .HasMaxLength(20);

                    b.Property<string>("Item24")
                        .HasMaxLength(20);

                    b.Property<string>("Item25")
                        .HasMaxLength(20);

                    b.Property<string>("Item26")
                        .HasMaxLength(20);

                    b.Property<string>("Item27")
                        .HasMaxLength(20);

                    b.Property<string>("Item28")
                        .HasMaxLength(20);

                    b.Property<string>("Item29")
                        .HasMaxLength(20);

                    b.Property<string>("Item3")
                        .HasMaxLength(20);

                    b.Property<string>("Item30")
                        .HasMaxLength(20);

                    b.Property<string>("Item31")
                        .HasMaxLength(20);

                    b.Property<string>("Item32")
                        .HasMaxLength(20);

                    b.Property<string>("Item33")
                        .HasMaxLength(20);

                    b.Property<string>("Item34")
                        .HasMaxLength(20);

                    b.Property<string>("Item35")
                        .HasMaxLength(20);

                    b.Property<string>("Item36")
                        .HasMaxLength(20);

                    b.Property<string>("Item37")
                        .HasMaxLength(20);

                    b.Property<string>("Item38")
                        .HasMaxLength(20);

                    b.Property<string>("Item39")
                        .HasMaxLength(20);

                    b.Property<string>("Item4")
                        .HasMaxLength(20);

                    b.Property<string>("Item40")
                        .HasMaxLength(20);

                    b.Property<string>("Item41")
                        .HasMaxLength(20);

                    b.Property<string>("Item42")
                        .HasMaxLength(20);

                    b.Property<string>("Item43")
                        .HasMaxLength(20);

                    b.Property<string>("Item44")
                        .HasMaxLength(20);

                    b.Property<string>("Item45")
                        .HasMaxLength(20);

                    b.Property<string>("Item46")
                        .HasMaxLength(20);

                    b.Property<string>("Item47")
                        .HasMaxLength(20);

                    b.Property<string>("Item48")
                        .HasMaxLength(20);

                    b.Property<string>("Item49")
                        .HasMaxLength(20);

                    b.Property<string>("Item5")
                        .HasMaxLength(20);

                    b.Property<string>("Item50")
                        .HasMaxLength(20);

                    b.Property<string>("Item6")
                        .HasMaxLength(20);

                    b.Property<string>("Item7")
                        .HasMaxLength(20);

                    b.Property<string>("Item8")
                        .HasMaxLength(20);

                    b.Property<string>("Item9")
                        .HasMaxLength(20);

                    b.Property<double?>("Rating1");

                    b.Property<double?>("Rating10");

                    b.Property<double?>("Rating11");

                    b.Property<double?>("Rating12");

                    b.Property<double?>("Rating13");

                    b.Property<double?>("Rating14");

                    b.Property<double?>("Rating15");

                    b.Property<double?>("Rating16");

                    b.Property<double?>("Rating17");

                    b.Property<double?>("Rating18");

                    b.Property<double?>("Rating19");

                    b.Property<double?>("Rating2");

                    b.Property<double?>("Rating20");

                    b.Property<double?>("Rating21");

                    b.Property<double?>("Rating22");

                    b.Property<double?>("Rating23");

                    b.Property<double?>("Rating24");

                    b.Property<double?>("Rating25");

                    b.Property<double?>("Rating26");

                    b.Property<double?>("Rating27");

                    b.Property<double?>("Rating28");

                    b.Property<double?>("Rating29");

                    b.Property<double?>("Rating3");

                    b.Property<double?>("Rating30");

                    b.Property<double?>("Rating31");

                    b.Property<double?>("Rating32");

                    b.Property<double?>("Rating33");

                    b.Property<double?>("Rating34");

                    b.Property<double?>("Rating35");

                    b.Property<double?>("Rating36");

                    b.Property<double?>("Rating37");

                    b.Property<double?>("Rating38");

                    b.Property<double?>("Rating39");

                    b.Property<double?>("Rating4");

                    b.Property<double?>("Rating40");

                    b.Property<double?>("Rating41");

                    b.Property<double?>("Rating42");

                    b.Property<double?>("Rating43");

                    b.Property<double?>("Rating44");

                    b.Property<double?>("Rating45");

                    b.Property<double?>("Rating46");

                    b.Property<double?>("Rating47");

                    b.Property<double?>("Rating48");

                    b.Property<double?>("Rating49");

                    b.Property<double?>("Rating5");

                    b.Property<double?>("Rating50");

                    b.Property<double?>("Rating6");

                    b.Property<double?>("Rating7");

                    b.Property<double?>("Rating8");

                    b.Property<double?>("Rating9");

                    b.HasKey("UserId");

                    b.ToTable("EnsembleRecommendation");
                });

            modelBuilder.Entity("RecSys.Models.FrequentSequentialPattern", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Sequence")
                        .IsRequired();

                    b.Property<int>("Support");

                    b.HasKey("Id");

                    b.ToTable("FrequentSequentialPattern2items-10Months");
                });

            modelBuilder.Entity("RecSys.Models.PurchaseHistoryRecommendation", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Item1")
                        .HasMaxLength(20);

                    b.Property<string>("Item10")
                        .HasMaxLength(20);

                    b.Property<string>("Item11")
                        .HasMaxLength(20);

                    b.Property<string>("Item12")
                        .HasMaxLength(20);

                    b.Property<string>("Item13")
                        .HasMaxLength(20);

                    b.Property<string>("Item14")
                        .HasMaxLength(20);

                    b.Property<string>("Item15")
                        .HasMaxLength(20);

                    b.Property<string>("Item16")
                        .HasMaxLength(20);

                    b.Property<string>("Item17")
                        .HasMaxLength(20);

                    b.Property<string>("Item18")
                        .HasMaxLength(20);

                    b.Property<string>("Item19")
                        .HasMaxLength(20);

                    b.Property<string>("Item2")
                        .HasMaxLength(20);

                    b.Property<string>("Item20")
                        .HasMaxLength(20);

                    b.Property<string>("Item21")
                        .HasMaxLength(20);

                    b.Property<string>("Item22")
                        .HasMaxLength(20);

                    b.Property<string>("Item23")
                        .HasMaxLength(20);

                    b.Property<string>("Item24")
                        .HasMaxLength(20);

                    b.Property<string>("Item25")
                        .HasMaxLength(20);

                    b.Property<string>("Item26")
                        .HasMaxLength(20);

                    b.Property<string>("Item27")
                        .HasMaxLength(20);

                    b.Property<string>("Item28")
                        .HasMaxLength(20);

                    b.Property<string>("Item29")
                        .HasMaxLength(20);

                    b.Property<string>("Item3")
                        .HasMaxLength(20);

                    b.Property<string>("Item30")
                        .HasMaxLength(20);

                    b.Property<string>("Item31")
                        .HasMaxLength(20);

                    b.Property<string>("Item32")
                        .HasMaxLength(20);

                    b.Property<string>("Item33")
                        .HasMaxLength(20);

                    b.Property<string>("Item34")
                        .HasMaxLength(20);

                    b.Property<string>("Item35")
                        .HasMaxLength(20);

                    b.Property<string>("Item36")
                        .HasMaxLength(20);

                    b.Property<string>("Item37")
                        .HasMaxLength(20);

                    b.Property<string>("Item38")
                        .HasMaxLength(20);

                    b.Property<string>("Item39")
                        .HasMaxLength(20);

                    b.Property<string>("Item4")
                        .HasMaxLength(20);

                    b.Property<string>("Item40")
                        .HasMaxLength(20);

                    b.Property<string>("Item41")
                        .HasMaxLength(20);

                    b.Property<string>("Item42")
                        .HasMaxLength(20);

                    b.Property<string>("Item43")
                        .HasMaxLength(20);

                    b.Property<string>("Item44")
                        .HasMaxLength(20);

                    b.Property<string>("Item45")
                        .HasMaxLength(20);

                    b.Property<string>("Item46")
                        .HasMaxLength(20);

                    b.Property<string>("Item47")
                        .HasMaxLength(20);

                    b.Property<string>("Item48")
                        .HasMaxLength(20);

                    b.Property<string>("Item49")
                        .HasMaxLength(20);

                    b.Property<string>("Item5")
                        .HasMaxLength(20);

                    b.Property<string>("Item50")
                        .HasMaxLength(20);

                    b.Property<string>("Item6")
                        .HasMaxLength(20);

                    b.Property<string>("Item7")
                        .HasMaxLength(20);

                    b.Property<string>("Item8")
                        .HasMaxLength(20);

                    b.Property<string>("Item9")
                        .HasMaxLength(20);

                    b.Property<double?>("Rating1");

                    b.Property<double?>("Rating10");

                    b.Property<double?>("Rating11");

                    b.Property<double?>("Rating12");

                    b.Property<double?>("Rating13");

                    b.Property<double?>("Rating14");

                    b.Property<double?>("Rating15");

                    b.Property<double?>("Rating16");

                    b.Property<double?>("Rating17");

                    b.Property<double?>("Rating18");

                    b.Property<double?>("Rating19");

                    b.Property<double?>("Rating2");

                    b.Property<double?>("Rating20");

                    b.Property<double?>("Rating21");

                    b.Property<double?>("Rating22");

                    b.Property<double?>("Rating23");

                    b.Property<double?>("Rating24");

                    b.Property<double?>("Rating25");

                    b.Property<double?>("Rating26");

                    b.Property<double?>("Rating27");

                    b.Property<double?>("Rating28");

                    b.Property<double?>("Rating29");

                    b.Property<double?>("Rating3");

                    b.Property<double?>("Rating30");

                    b.Property<double?>("Rating31");

                    b.Property<double?>("Rating32");

                    b.Property<double?>("Rating33");

                    b.Property<double?>("Rating34");

                    b.Property<double?>("Rating35");

                    b.Property<double?>("Rating36");

                    b.Property<double?>("Rating37");

                    b.Property<double?>("Rating38");

                    b.Property<double?>("Rating39");

                    b.Property<double?>("Rating4");

                    b.Property<double?>("Rating40");

                    b.Property<double?>("Rating41");

                    b.Property<double?>("Rating42");

                    b.Property<double?>("Rating43");

                    b.Property<double?>("Rating44");

                    b.Property<double?>("Rating45");

                    b.Property<double?>("Rating46");

                    b.Property<double?>("Rating47");

                    b.Property<double?>("Rating48");

                    b.Property<double?>("Rating49");

                    b.Property<double?>("Rating5");

                    b.Property<double?>("Rating50");

                    b.Property<double?>("Rating6");

                    b.Property<double?>("Rating7");

                    b.Property<double?>("Rating8");

                    b.Property<double?>("Rating9");

                    b.HasKey("UserId");

                    b.ToTable("PurchaseHistoryRecommendation");
                });

            modelBuilder.Entity("RecSys.Models.Recommendation", b =>
                {
                    b.Property<int>("RecommendationInfoId");

                    b.Property<string>("Item1")
                        .HasMaxLength(20);

                    b.Property<string>("Item10")
                        .HasMaxLength(20);

                    b.Property<string>("Item11")
                        .HasMaxLength(20);

                    b.Property<string>("Item12")
                        .HasMaxLength(20);

                    b.Property<string>("Item13")
                        .HasMaxLength(20);

                    b.Property<string>("Item14")
                        .HasMaxLength(20);

                    b.Property<string>("Item15")
                        .HasMaxLength(20);

                    b.Property<string>("Item16")
                        .HasMaxLength(20);

                    b.Property<string>("Item17")
                        .HasMaxLength(20);

                    b.Property<string>("Item18")
                        .HasMaxLength(20);

                    b.Property<string>("Item19")
                        .HasMaxLength(20);

                    b.Property<string>("Item2")
                        .HasMaxLength(20);

                    b.Property<string>("Item20")
                        .HasMaxLength(20);

                    b.Property<string>("Item21")
                        .HasMaxLength(20);

                    b.Property<string>("Item22")
                        .HasMaxLength(20);

                    b.Property<string>("Item23")
                        .HasMaxLength(20);

                    b.Property<string>("Item24")
                        .HasMaxLength(20);

                    b.Property<string>("Item25")
                        .HasMaxLength(20);

                    b.Property<string>("Item26")
                        .HasMaxLength(20);

                    b.Property<string>("Item27")
                        .HasMaxLength(20);

                    b.Property<string>("Item28")
                        .HasMaxLength(20);

                    b.Property<string>("Item29")
                        .HasMaxLength(20);

                    b.Property<string>("Item3")
                        .HasMaxLength(20);

                    b.Property<string>("Item30")
                        .HasMaxLength(20);

                    b.Property<string>("Item31")
                        .HasMaxLength(20);

                    b.Property<string>("Item32")
                        .HasMaxLength(20);

                    b.Property<string>("Item33")
                        .HasMaxLength(20);

                    b.Property<string>("Item34")
                        .HasMaxLength(20);

                    b.Property<string>("Item35")
                        .HasMaxLength(20);

                    b.Property<string>("Item36")
                        .HasMaxLength(20);

                    b.Property<string>("Item37")
                        .HasMaxLength(20);

                    b.Property<string>("Item38")
                        .HasMaxLength(20);

                    b.Property<string>("Item39")
                        .HasMaxLength(20);

                    b.Property<string>("Item4")
                        .HasMaxLength(20);

                    b.Property<string>("Item40")
                        .HasMaxLength(20);

                    b.Property<string>("Item41")
                        .HasMaxLength(20);

                    b.Property<string>("Item42")
                        .HasMaxLength(20);

                    b.Property<string>("Item43")
                        .HasMaxLength(20);

                    b.Property<string>("Item44")
                        .HasMaxLength(20);

                    b.Property<string>("Item45")
                        .HasMaxLength(20);

                    b.Property<string>("Item46")
                        .HasMaxLength(20);

                    b.Property<string>("Item47")
                        .HasMaxLength(20);

                    b.Property<string>("Item48")
                        .HasMaxLength(20);

                    b.Property<string>("Item49")
                        .HasMaxLength(20);

                    b.Property<string>("Item5")
                        .HasMaxLength(20);

                    b.Property<string>("Item50")
                        .HasMaxLength(20);

                    b.Property<string>("Item6")
                        .HasMaxLength(20);

                    b.Property<string>("Item7")
                        .HasMaxLength(20);

                    b.Property<string>("Item8")
                        .HasMaxLength(20);

                    b.Property<string>("Item9")
                        .HasMaxLength(20);

                    b.Property<double?>("Rating1");

                    b.Property<double?>("Rating10");

                    b.Property<double?>("Rating11");

                    b.Property<double?>("Rating12");

                    b.Property<double?>("Rating13");

                    b.Property<double?>("Rating14");

                    b.Property<double?>("Rating15");

                    b.Property<double?>("Rating16");

                    b.Property<double?>("Rating17");

                    b.Property<double?>("Rating18");

                    b.Property<double?>("Rating19");

                    b.Property<double?>("Rating2");

                    b.Property<double?>("Rating20");

                    b.Property<double?>("Rating21");

                    b.Property<double?>("Rating22");

                    b.Property<double?>("Rating23");

                    b.Property<double?>("Rating24");

                    b.Property<double?>("Rating25");

                    b.Property<double?>("Rating26");

                    b.Property<double?>("Rating27");

                    b.Property<double?>("Rating28");

                    b.Property<double?>("Rating29");

                    b.Property<double?>("Rating3");

                    b.Property<double?>("Rating30");

                    b.Property<double?>("Rating31");

                    b.Property<double?>("Rating32");

                    b.Property<double?>("Rating33");

                    b.Property<double?>("Rating34");

                    b.Property<double?>("Rating35");

                    b.Property<double?>("Rating36");

                    b.Property<double?>("Rating37");

                    b.Property<double?>("Rating38");

                    b.Property<double?>("Rating39");

                    b.Property<double?>("Rating4");

                    b.Property<double?>("Rating40");

                    b.Property<double?>("Rating41");

                    b.Property<double?>("Rating42");

                    b.Property<double?>("Rating43");

                    b.Property<double?>("Rating44");

                    b.Property<double?>("Rating45");

                    b.Property<double?>("Rating46");

                    b.Property<double?>("Rating47");

                    b.Property<double?>("Rating48");

                    b.Property<double?>("Rating49");

                    b.Property<double?>("Rating5");

                    b.Property<double?>("Rating50");

                    b.Property<double?>("Rating6");

                    b.Property<double?>("Rating7");

                    b.Property<double?>("Rating8");

                    b.Property<double?>("Rating9");

                    b.Property<int>("UserId");

                    b.HasKey("RecommendationInfoId");

                    b.ToTable("Recommendation");
                });

            modelBuilder.Entity("RecSys.Models.RecommendationInfo", b =>
                {
                    b.Property<int>("RecId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RecName")
                        .HasMaxLength(50);

                    b.HasKey("RecId");

                    b.ToTable("RecommendationInfo");
                });

            modelBuilder.Entity("RecSys.Models.SequentialRecommendation", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Item1")
                        .HasMaxLength(20);

                    b.Property<string>("Item10")
                        .HasMaxLength(20);

                    b.Property<string>("Item11")
                        .HasMaxLength(20);

                    b.Property<string>("Item12")
                        .HasMaxLength(20);

                    b.Property<string>("Item13")
                        .HasMaxLength(20);

                    b.Property<string>("Item14")
                        .HasMaxLength(20);

                    b.Property<string>("Item15")
                        .HasMaxLength(20);

                    b.Property<string>("Item16")
                        .HasMaxLength(20);

                    b.Property<string>("Item17")
                        .HasMaxLength(20);

                    b.Property<string>("Item18")
                        .HasMaxLength(20);

                    b.Property<string>("Item19")
                        .HasMaxLength(20);

                    b.Property<string>("Item2")
                        .HasMaxLength(20);

                    b.Property<string>("Item20")
                        .HasMaxLength(20);

                    b.Property<string>("Item21")
                        .HasMaxLength(20);

                    b.Property<string>("Item22")
                        .HasMaxLength(20);

                    b.Property<string>("Item23")
                        .HasMaxLength(20);

                    b.Property<string>("Item24")
                        .HasMaxLength(20);

                    b.Property<string>("Item25")
                        .HasMaxLength(20);

                    b.Property<string>("Item26")
                        .HasMaxLength(20);

                    b.Property<string>("Item27")
                        .HasMaxLength(20);

                    b.Property<string>("Item28")
                        .HasMaxLength(20);

                    b.Property<string>("Item29")
                        .HasMaxLength(20);

                    b.Property<string>("Item3")
                        .HasMaxLength(20);

                    b.Property<string>("Item30")
                        .HasMaxLength(20);

                    b.Property<string>("Item31")
                        .HasMaxLength(20);

                    b.Property<string>("Item32")
                        .HasMaxLength(20);

                    b.Property<string>("Item33")
                        .HasMaxLength(20);

                    b.Property<string>("Item34")
                        .HasMaxLength(20);

                    b.Property<string>("Item35")
                        .HasMaxLength(20);

                    b.Property<string>("Item36")
                        .HasMaxLength(20);

                    b.Property<string>("Item37")
                        .HasMaxLength(20);

                    b.Property<string>("Item38")
                        .HasMaxLength(20);

                    b.Property<string>("Item39")
                        .HasMaxLength(20);

                    b.Property<string>("Item4")
                        .HasMaxLength(20);

                    b.Property<string>("Item40")
                        .HasMaxLength(20);

                    b.Property<string>("Item41")
                        .HasMaxLength(20);

                    b.Property<string>("Item42")
                        .HasMaxLength(20);

                    b.Property<string>("Item43")
                        .HasMaxLength(20);

                    b.Property<string>("Item44")
                        .HasMaxLength(20);

                    b.Property<string>("Item45")
                        .HasMaxLength(20);

                    b.Property<string>("Item46")
                        .HasMaxLength(20);

                    b.Property<string>("Item47")
                        .HasMaxLength(20);

                    b.Property<string>("Item48")
                        .HasMaxLength(20);

                    b.Property<string>("Item49")
                        .HasMaxLength(20);

                    b.Property<string>("Item5")
                        .HasMaxLength(20);

                    b.Property<string>("Item50")
                        .HasMaxLength(20);

                    b.Property<string>("Item6")
                        .HasMaxLength(20);

                    b.Property<string>("Item7")
                        .HasMaxLength(20);

                    b.Property<string>("Item8")
                        .HasMaxLength(20);

                    b.Property<string>("Item9")
                        .HasMaxLength(20);

                    b.Property<double?>("Rating1");

                    b.Property<double?>("Rating10");

                    b.Property<double?>("Rating11");

                    b.Property<double?>("Rating12");

                    b.Property<double?>("Rating13");

                    b.Property<double?>("Rating14");

                    b.Property<double?>("Rating15");

                    b.Property<double?>("Rating16");

                    b.Property<double?>("Rating17");

                    b.Property<double?>("Rating18");

                    b.Property<double?>("Rating19");

                    b.Property<double?>("Rating2");

                    b.Property<double?>("Rating20");

                    b.Property<double?>("Rating21");

                    b.Property<double?>("Rating22");

                    b.Property<double?>("Rating23");

                    b.Property<double?>("Rating24");

                    b.Property<double?>("Rating25");

                    b.Property<double?>("Rating26");

                    b.Property<double?>("Rating27");

                    b.Property<double?>("Rating28");

                    b.Property<double?>("Rating29");

                    b.Property<double?>("Rating3");

                    b.Property<double?>("Rating30");

                    b.Property<double?>("Rating31");

                    b.Property<double?>("Rating32");

                    b.Property<double?>("Rating33");

                    b.Property<double?>("Rating34");

                    b.Property<double?>("Rating35");

                    b.Property<double?>("Rating36");

                    b.Property<double?>("Rating37");

                    b.Property<double?>("Rating38");

                    b.Property<double?>("Rating39");

                    b.Property<double?>("Rating4");

                    b.Property<double?>("Rating40");

                    b.Property<double?>("Rating41");

                    b.Property<double?>("Rating42");

                    b.Property<double?>("Rating43");

                    b.Property<double?>("Rating44");

                    b.Property<double?>("Rating45");

                    b.Property<double?>("Rating46");

                    b.Property<double?>("Rating47");

                    b.Property<double?>("Rating48");

                    b.Property<double?>("Rating49");

                    b.Property<double?>("Rating5");

                    b.Property<double?>("Rating50");

                    b.Property<double?>("Rating6");

                    b.Property<double?>("Rating7");

                    b.Property<double?>("Rating8");

                    b.Property<double?>("Rating9");

                    b.HasKey("UserId");

                    b.ToTable("SequentialRecommendation");
                });

            modelBuilder.Entity("RecSys.Models.UkRetailOriginalSales", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .IsRequired();

                    b.Property<int?>("CustomerID");

                    b.Property<string>("Description");

                    b.Property<DateTime>("InvoiceDate");

                    b.Property<int?>("InvoiceNo")
                        .HasColumnType("int");

                    b.Property<int>("Quantity");

                    b.Property<string>("StockCode")
                        .IsRequired();

                    b.Property<int>("UnitPrice");

                    b.HasKey("Id");

                    b.ToTable("UkRetailOriginalSales");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RecSys.Models.Recommendation", b =>
                {
                    b.HasOne("RecSys.Models.RecommendationInfo")
                        .WithMany("Recommendations")
                        .HasForeignKey("RecommendationInfoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
